### ISSUE TITLE
Couldn't run this on 32bit Windows 7

### ISSUE THREAD

**Issue by firewire10000** [jhdcruz/Desktop-Messages#14]
Are they're any dependencies before running this? I just kept on getting a message saying this it can't run on this architecture of Windows.

**Comment by jhdcruz** [comment]
I'm sorry but it only supports x64 Architectures. I haven't found a way to build this in a x32 using `electron-packager`.

Update:
   Latest update of `electron-packager` drops the support for `x32` architectures.
